import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ScrollArea } from "@/components/ui/scroll-area";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  icons:"/assets/icon/icon.png",
  title: "Mango Disease Detection",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className+" font-san bg-background md:bg-muted/80 dark:bg-background md:dark:bg-muted/20"}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ScrollArea>
              {children}
            </ScrollArea>
          </ThemeProvider>
      </body>
    </html>
  );
}
