import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ScrollArea } from "@/components/ui/scroll-area";
import { AuthProvider } from "@/context/auth-context";


export const metadata: Metadata = {
  title: "Mango Disease Detection",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/icon/icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply the Inter font */}
      <body className={" font-sans bg-background relative"}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <ScrollArea>{children}</ScrollArea>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
